CONTAINER Oconnectiongrid {
    INCLUDE Obase;
    NAME Oconnectiongrid;
    GROUP ID_OBJECTPROPERTIES {
    }
    GROUP CONNECTION_GRID_NETWORK_CONNECTION_GROUP {
        DEFAULT 1;
        REAL CONNECTION_GRID_NETWORK_CONNECTION_GRID_UNIT_LENGTH { DEFAULT 10.0; STEP 1.0; }
        LONG CONNECTION_GRID_NETWORK_CONNECTION_ORDER {
            DEFAULT CONNECTION_GRID_NETWORK_CONNECTION_ORDER_XYZ;
            CYCLE {
                CONNECTION_GRID_NETWORK_CONNECTION_ORDER_XYZ;
                CONNECTION_GRID_NETWORK_CONNECTION_ORDER_XZY;
                CONNECTION_GRID_NETWORK_CONNECTION_ORDER_YXZ;
                CONNECTION_GRID_NETWORK_CONNECTION_ORDER_YZX;
                CONNECTION_GRID_NETWORK_CONNECTION_ORDER_ZYX;
                CONNECTION_GRID_NETWORK_CONNECTION_ORDER_ZXY;
            }
        }
    }
}
