#pragma once
enum {
    Oconnectiongrid = 1053026,
    CONNECTION_GRID_NETWORK_CONNECTION_GROUP = 1000,
    CONNECTION_GRID_NETWORK_CONNECTION_GRID_UNIT_LENGTH = 1001,
    CONNECTION_GRID_NETWORK_CONNECTION_ORDER = 1002,
        CONNECTION_GRID_NETWORK_CONNECTION_ORDER_XYZ = 1,
        CONNECTION_GRID_NETWORK_CONNECTION_ORDER_XZY = 2,
        CONNECTION_GRID_NETWORK_CONNECTION_ORDER_YXZ = 3,
        CONNECTION_GRID_NETWORK_CONNECTION_ORDER_YZX = 4,
        CONNECTION_GRID_NETWORK_CONNECTION_ORDER_ZYX = 5,
        CONNECTION_GRID_NETWORK_CONNECTION_ORDER_ZXY = 6,
};
